
services:
  jellyfin-automations:
    build: .
    ports:
      - "10691:10691"
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
    volumes:
      - .:/app